### ISSUE TITLE
Review QC template

### ISSUE THREAD

**Issue by jeff-m-sullivan** [EntityRisk/.github#1]
Please review the template issue that I created and make sure it lines up with any QC language we've had in protocols.

If you can think of anything else that we should add, please go ahead.

**Comment by andrew-p-morris-er** [comment]
This looks great, I would just add one thing and pass along one quick question:

1. In the step ‘A second set of eyes has reviewed all the code…’ I might add: ‘and the reviewer has recorded all questions and comments, technical and otherwise, to be resolved with the writer(s) of the code.’ This might seem obvious, but I figure it can’t hurt to set an explicit expectation that review is very much an ‘active reading’ process.

2. One thing I’ve done previously, though it might not be applicable here, is to actually have a second person independently implement (i.e. code) methods underlying a deliverable analysis.  This is quite a time commitment, and is probably best reserved for more complex problems, but I’d be curious to hear your thoughts on it.

**Comment by jeff-m-sullivan** [comment]
Test comment.

**Comment by jeff-m-sullivan** [comment]
Closed by 7064e15332b6b0b76cf8feeb2cf3d6583ecef5d6
